# Generated by Django 5.2.4 on 2026-09-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_pricee',
            new_name='total_price',
        ),
    ]
